/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fideairlines.Server.View;

import com.mycompany.fideairlines.Server.Entities.Destination;
import com.mycompany.fideairlines.Server.Entities.Fly;
import com.mycompany.fideairlines.Server.Utils.Category;
import com.mycompany.fideairlines.Server.Utils.DBconexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class RegistrarVuelos extends javax.swing.JFrame {

    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

    public RegistrarVuelos() {
        initComponents();
        cargarDestinos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Benviar = new javax.swing.JButton();
        TAfechaentrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TAfechasalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TAnumvuelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TAprecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CBclases = new javax.swing.JComboBox<>();
        CBdestinos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BTvolverMenu = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 180, 255));
        jPanel2.setFocusCycleRoot(true);

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));

        Benviar.setBackground(new java.awt.Color(153, 153, 153));
        Benviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Benviar.setForeground(new java.awt.Color(255, 255, 255));
        Benviar.setText("Enviar");
        Benviar.setBorder(null);
        Benviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenviarActionPerformed(evt);
            }
        });

        TAfechaentrada.setBackground(new java.awt.Color(89, 79, 79));
        TAfechaentrada.setForeground(new java.awt.Color(255, 255, 255));
        TAfechaentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAfechaentradaActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha de entrada:");

        TAfechasalida.setBackground(new java.awt.Color(89, 79, 79));
        TAfechasalida.setForeground(new java.awt.Color(255, 255, 255));
        TAfechasalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAfechasalidaActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha de salida:");

        TAnumvuelo.setBackground(new java.awt.Color(89, 79, 79));
        TAnumvuelo.setForeground(new java.awt.Color(255, 255, 255));
        TAnumvuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAnumvueloActionPerformed(evt);
            }
        });

        jLabel2.setText("Número de vuelo:");

        jLabel7.setText("Clase:");

        jLabel8.setText("Precio:");

        TAprecio.setBackground(new java.awt.Color(89, 79, 79));
        TAprecio.setForeground(new java.awt.Color(255, 255, 255));
        TAprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAprecioActionPerformed(evt);
            }
        });

        jLabel9.setText("Destino:");

        CBclases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primera Clase", "Clase Business", "Clase Turista" }));
        CBclases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBclasesActionPerformed(evt);
            }
        });

        CBdestinos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Benviar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CBdestinos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBclases, javax.swing.GroupLayout.Alignment.LEADING, 0, 220, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TAnumvuelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(TAfechasalida, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TAfechaentrada, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TAprecio, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(286, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TAnumvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TAfechasalida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TAfechaentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBclases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TAprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(CBdestinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Benviar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrando vuelos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("FideAirline");

        BTvolverMenu.setText("Volver al menu");
        BTvolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTvolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTvolverMenu)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BTvolverMenu))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenviarActionPerformed
        if (TAnumvuelo.getText().isEmpty() || TAfechasalida.getText().isEmpty() || TAfechaentrada.getText().isEmpty() || TAprecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Uno o más campos vacíos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            formatoFecha.setLenient(false); // Evita fechas inválidas
            try {
                formatoFecha.parse(TAfechaentrada.getText());
                formatoFecha.parse(TAfechasalida.getText());

                ArrayList<Destination> destinos = new ArrayList<>();

                Connection nuevaConexion = DBconexion.ConectarBD();

                String comando_Select = "SELECT id, nombre, horasViaje FROM destinos";
                PreparedStatement nuevoStatamentPreparado = nuevaConexion.prepareStatement(comando_Select);

                ResultSet rs = nuevoStatamentPreparado.executeQuery();

                while (rs.next()) {
                    int id = rs.getInt("id");
                    String nombre = rs.getString("nombre");
                    String horasViaje = rs.getString("horasViaje");
                    Destination destino = new Destination(id, nombre, horasViaje);
                    destinos.add(destino);
                }

                rs.close();
                nuevoStatamentPreparado.close();
                nuevaConexion.close();

                int num = CBclases.getSelectedIndex();

                int indexDestinoSeleccionado = CBdestinos.getSelectedIndex();

                if (indexDestinoSeleccionado >= 0 && indexDestinoSeleccionado < destinos.size()) {
                    Destination destinoSeleccionado = destinos.get(indexDestinoSeleccionado);

                    if (num == 0) {
                        Fly vuelo = new Fly(Integer.parseInt(TAnumvuelo.getText()), TAfechasalida.getText(), TAfechaentrada.getText(), Double.parseDouble(TAprecio.getText()), destinoSeleccionado.getNombre());
                        vuelo.setClase(Category.FIRST_CLASS);
                        vuelo.guardarVueloDB(vuelo);
                    } else if (num == 1) {
                        Fly vuelo = new Fly(Integer.parseInt(TAnumvuelo.getText()), TAfechasalida.getText(), TAfechaentrada.getText(), Double.parseDouble(TAprecio.getText()), destinoSeleccionado.getNombre());
                        vuelo.setClase(Category.BUSINESS);
                        vuelo.guardarVueloDB(vuelo);
                    } else {
                        Fly vuelo = new Fly(Integer.parseInt(TAnumvuelo.getText()), TAfechasalida.getText(), TAfechaentrada.getText(), Double.parseDouble(TAprecio.getText()), destinoSeleccionado.getNombre());
                        vuelo.setClase(Category.ECONOMY);
                        vuelo.guardarVueloDB(vuelo);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El destino seleccionado no fue encontrado en la base de datos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException | ParseException e) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BenviarActionPerformed
    private void cargarDestinos() {
        try {
            // Creamos la conexión con la base de datos
            Connection nuevaConexion = DBconexion.ConectarBD();

            // Definimos el comando para obtener los destinos
            String comando_Select = "SELECT id, nombre, horasViaje FROM destinos";
            PreparedStatement nuevoStatamentPreparado = nuevaConexion.prepareStatement(comando_Select);

            // Ejecutamos la consulta
            ResultSet rs = nuevoStatamentPreparado.executeQuery();

            ArrayList<Destination> destinos = new ArrayList<>();

            // Recorremos los resultados y creamos objetos Destination
            while (rs.next()) {
                int id = rs.getInt("id");
                String nombre = rs.getString("nombre");
                String horasViaje = rs.getString("horasViaje");
                Destination destino = new Destination(id, nombre, horasViaje);
                destinos.add(destino);
            }

            // Cerramos la conexión y los recursos
            rs.close();
            nuevoStatamentPreparado.close();
            nuevaConexion.close();

            // Limpiamos el JComboBox CBdestinos
            CBdestinos.removeAllItems();

            // Agregamos los destinos al JComboBox CBdestinos
            for (Destination destino : destinos) {
                CBdestinos.addItem(destino.getNombre()); // Agregar objetos Destination directamente
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar los destinos. Error: " + ex.getMessage());
        }
    }
    private void TAfechaentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAfechaentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAfechaentradaActionPerformed

    private void TAfechasalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAfechasalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAfechasalidaActionPerformed

    private void TAnumvueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAnumvueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAnumvueloActionPerformed

    private void TAprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAprecioActionPerformed

    private void CBclasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBclasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBclasesActionPerformed

    private void BTvolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTvolverMenuActionPerformed
        // TODO add your handling code here:
        MenuServer m = new MenuServer();
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BTvolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTvolverMenu;
    private javax.swing.JButton Benviar;
    private javax.swing.JComboBox<String> CBclases;
    private javax.swing.JComboBox<String> CBdestinos;
    private javax.swing.JTextField TAfechaentrada;
    private javax.swing.JTextField TAfechasalida;
    private javax.swing.JTextField TAnumvuelo;
    private javax.swing.JTextField TAprecio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
